### ISSUE TITLE
Error executing process > 'NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN_IGENOMES

### ISSUE THREAD

**Issue by angpiz** [MonashBioinformaticsPlatform/laxy#273] opened 2023-03-03 01:14 UTC
Hello!

I've run 3 times the same samples and I got this error twice:

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 105.

The full error message was:

Error executing process > 'NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN_IGENOMES (IR1-1-3)'

Caused by:
  Process `NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN_IGENOMES (IR1-1-3)` terminated with an error exit status (105)

Command executed:

  STAR \
      --genomeDir STARIndex \
      --readFilesIn IR1-1-3_1_val_1.fq.gz IR1-1-3_2_val_2.fq.gz  \
      --runThreadN 48 \
      --outFileNamePrefix IR1-1-3. \
       \
      --sjdbGTFfile genes.gtf \
      --outSAMattrRGline ID:IR1-1-3 'SM:IR1-1-3'   \
      --quantMode TranscriptomeSAM --twopassMode Basic --outSAMtype BAM Unsorted --readFilesCommand zcat --runRNGseed 0 --outFilterMultimapNmax 20 --alignSJDBoverhangMin 1 --outSAMattributes NH HI AS NM MD --quantTranscriptomeBan Singleend --outSAMstrandField intronMotif
  
  
  
  if [ -f IR1-1-3.Unmapped.out.mate1 ]; then
      mv IR1-1-3.Unmapped.out.mate1 IR1-1-3.unmapped_1.fastq
      gzip IR1-1-3.unmapped_1.fastq
  fi
  if [ -f IR1-1-3.Unmapped.out.mate2 ]; then
      mv IR1-1-3.Unmapped.out.mate2 IR1-1-3.unmapped_2.fastq
      gzip IR1-1-3.unmapped_2.fastq
  fi
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN_IGENOMES":
      star: $(STAR --version | sed -e "s/STAR_//g")
      samtools: $(echo $(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*$//')
      gawk: $(echo $(gawk --version 2>&1) | sed 's/^.*GNU Awk //; s/, .*$//')
  END_VERSIONS

Command exit status:
  105

Command output:
  Mar 01 19:20:37 ..... started STAR run
  Mar 01 19:20:37 ..... loading genome

Command error:
  WARNING: Skipping mount /usr/local/singularity/3.9.2/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  
  EXITING because of FATAL ERROR: could not open genome file STARIndex/genomeParameters.txt
  SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
  
  Mar 01 19:20:37 ...... FATAL ERROR, exiting

Work dir:
  /fs03/pl41/laxy/jobs/3puYZHNXk9x0qH8i3n2VAT/output/work/36/e43463e8f223b35fa3419865cfc2c1

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

Is there something I can do on my end apart from restarting the pipeline?

A gene count file is produced but it's incomplete, about 250 genes do not get a count.

Thank you!
Angela

**Comment by pansapiens** [comment] 2023-03-03 05:05
Hi @angpiz - this is a problem on the production service I been working on debugging this week. It's not 100% reproducible, and it's unclear if it's a Nextflow or nf-core bug, or just a quirk of network connectivity/filesystem on the backend cluster. I've established that it only impacts the pre-defined 'iGenomes' references (which in the background are downloaded from AWS S3).

It will work if you instead use the 'externally provided reference genome' option with:

**sequence**
http://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz

**annotation**
http://ftp.ensembl.org/pub/release-109/gtf/homo_sapiens/Homo_sapiens.GRCh38.109.gtf.gz

This is probably a better choice anyway, since it's past time to retire the iGenomes references for more up-to-date ones.

**Comment by angpiz** [comment] 2023-03-06 06:06
Thank you Andrew, it worked!
Angela

From: Andrew Perry ***@***.***>
Date: Friday, 3 March 2023 at 4:06 pm
To: MonashBioinformaticsPlatform/laxy ***@***.***>
Cc: Angela Pizzolla ***@***.***>, Mention ***@***.***>
Subject: Re: [MonashBioinformaticsPlatform/laxy] Error executing process > 'NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN_IGENOMES (Issue #273)
! EXTERNAL EMAIL: Think before you click. If suspicious send to ***@***.***

Hi @angpiz<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fangpiz&umid=abccb173-d77f-4ff4-a6d3-755c974b73af&auth=4d41e25c5d761d3d9b3f3fb6ac781e525dd700b4-77ee35d767bd6dc351a8ec703434ca44bac20183> - this is a problem on the production service I been working on debugging this week. It's not 100% reproducible, and it's unclear if it's a Nextflow or nf-core bug, or just a quirk of network connectivity/filesystem on the backend cluster. I've established that it only impacts the pre-defined 'iGenomes' references (which in the background are downloaded from AWS S3).

It will work if you instead use the 'externally provided reference genome' option with:

sequence
http://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz

annotation
http://ftp.ensembl.org/pub/release-109/gtf/homo_sapiens/Homo_sapiens.GRCh38.109.gtf.gz

This is probably a better choice anyway, since it's past time to retire the iGenomes references for more up-to-date ones.

—
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fMonashBioinformaticsPlatform%2flaxy%2fissues%2f273%23issuecomment%2d1452979966&umid=abccb173-d77f-4ff4-a6d3-755c974b73af&auth=4d41e25c5d761d3d9b3f3fb6ac781e525dd700b4-c4ff3f1fdd32a87b38bc2dcb1ce7e42f37feca3a>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fA4XUGZEBDFR3UDFCCCVGOT3W2F34BANCNFSM6AAAAAAVOANW2Y&umid=abccb173-d77f-4ff4-a6d3-755c974b73af&auth=4d41e25c5d761d3d9b3f3fb6ac781e525dd700b4-74cec3bb724d090df9b14271af7c7da437eb9e15>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


Disclaimer: This email (including any attachments or links) may contain confidential and/or legally privileged information and is intended only to be read or used by the addressee. If you are not the intended addressee, any use, distribution, disclosure or copying of this email is strictly prohibited. Confidentiality and legal privilege attached to this email (including any attachments) are not waived or lost by reason of its mistaken delivery to you. If you have received this email in error, please delete it and notify us immediately by telephone or email. Peter MacCallum Cancer Centre provides no guarantee that this transmission is free of virus or that it has not been intercepted or altered and will not be liable for any delay in its receipt.

**Comment by pansapiens** [comment] 2023-03-09 02:56
Hi @angpiz, this should be resolved on production now by commit [3f48181](https://github.com/MonashBioinformaticsPlatform/laxy/commit/3f48181ad4ec640b940e2c7ec082611c5ac60224) and using pre-cached copies of the references rather than downloading them on demand. I'll close this issue for now, but note that this is more of a stop-gap measure and the handling of reference genomes by Laxy really needs to be overhauled (and migrated away from using iGenomes).

**Closed by pansapiens** 2023-03-09 02:56 UTC
Labels: bug
